#ifndef __CONST__H__
#define __CONST__H__

#define PLUGIN_VERSION	"v5.0"
#define PLUGIN_TITLE	" 3.x Plus"

#define SI_BUF_SIZE			256
#define SI_PATH_SIZE        (SI_BUF_SIZE*2)

#define SI_CLASSNAME_FRAME	"si_frame"
#define SI_CLASSNAME_MDI	"MDIClient"

#define SI_TAB_HEIGHT		24
#define SI_TAB_CLOSE_IDX	0

#define IDM_TAB_CTL_SUB_MENU 0x1000
#define IDM_CLOSE_CUR_FILE   0x1001
#define IDM_CLOSE_OTHER_FILE 0X1002
#define IDM_CLOSE_ALL_FILE   0X1003
#define IDM_OPEN_CUR_DIR     0x1011
#define IDM_OPEN_CUR_DIR_CMDLINE 0x1012
#define IDM_SET_ONLY_READ	 0x1013
#define IDM_CLR_ONLY_READ	 0x1014
#define IDM_CPY_FILE_PATH_TO_BOARD 0x1015
#define IDM_CPY_FILE_NAME_TO_BOARD 0x1016
#define IDM_CPY_CUR_PATH_TO_BOARD  0X1017
#define IDM_SVN_UPDATE_CUR_FILE 0x1018
#define IDM_SVN_UPDATE_CUR_PATH 0x1019

#endif